const FETCH_ORGS = 'FETCH_ORGS';
const SHOW_DIALOG_WINDOW = 'SHOW_DIALOG_WINDOW';

const GET_USER = 'GET_USER';
const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export {
  FETCH_ORGS,
  SHOW_DIALOG_WINDOW,
  GET_USER,
  SIGN_IN_ERROR
};